import { BASE_API_URL } from "./api";

const HOME_ROUTE = "/";
const ROUTE_SEPARATOR = "/";

const SCHEMA_TYPES = {
  ISSUANCE_COSTS: 'issuancecosts',
  BOND: 'bond'
};

const ACTIONS_BONDS = {
    CALCULATE_INITIAL: 'calculate-initial',
    CALCULATE_FINAL_COSTS: 'calculate-final-costs',
    YIELDS: 'yields',
    PAYMENT_SCHEDULE: 'payment-schedule'
}

const IAM_ENDPOINTS = {
    LOGIN: 'login'
}

export const ISSUANCE_COSTS_ROUTES = {
    ROUTE_GET_ALL: () => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.ISSUANCE_COSTS}`,
    ROUTE_UPDATE: () => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.ISSUANCE_COSTS}`,
    ROUTE_CREATE: () => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.ISSUANCE_COSTS}`,
    ROUTE_GET_BY_ID: (id : string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.ISSUANCE_COSTS}${ROUTE_SEPARATOR}${id}`,
    ROUTE_DELETE: (id : string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.ISSUANCE_COSTS}${ROUTE_SEPARATOR}${id}`
}

export const BOND_ROUTES = {
    ROUTE_GET_ALL: () => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}`,
    ROUTE_UPDATE: () => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}`,
    ROUTE_CREATE: () => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}`,
    ROUTE_GET_BY_ID: (id : string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}${ROUTE_SEPARATOR}${id}`,
    ROUTE_DELETE: (id : string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}${ROUTE_SEPARATOR}${id}`,
    ROUTE_CALCULATE_INITIAL_BY_ID: (id: string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}${ROUTE_SEPARATOR}${ACTIONS_BONDS.CALCULATE_INITIAL}${ROUTE_SEPARATOR}${id}`,
    ROUTE_CALCULATE_FINAL_COSTS_BY_ID: (id: string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}${ROUTE_SEPARATOR}${ACTIONS_BONDS.CALCULATE_FINAL_COSTS}${ROUTE_SEPARATOR}${id}`,
    ROUTE_YIELDS_BY_ID: (id: string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}${ROUTE_SEPARATOR}${ACTIONS_BONDS.YIELDS}${ROUTE_SEPARATOR}${id}`,
    ROUTE_PAYMENT_SCHEDULE_BY_ID: (id: string) => `${BASE_API_URL}${HOME_ROUTE}${SCHEMA_TYPES.BOND}${ROUTE_SEPARATOR}${ACTIONS_BONDS.PAYMENT_SCHEDULE}${ROUTE_SEPARATOR}${id}`
}

export const IAM_ROUTES = {
    ROUTE_LOGIN: () => `${BASE_API_URL}${HOME_ROUTE}${IAM_ENDPOINTS.LOGIN}`
}